# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [5]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [6]:
# Create a 1-dimensional NumPy array using np.array()
arr1=np.array([1,3,5,7])

# Create a 2-dimensional NumPy array using np.array()
arr2=np.array([[2,4,6],
               [8,10,12]])

# Create a 3-dimensional Numpy array using np.array()
arr3=np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[1,2,3],
               [4,5,6],
               [7,8,9]],
               [[1,2,3],
               [4,5,6],
               [7,8,9]]
              ])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [7]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(arr1)
arr1.shape,arr1.size,arr1.ndim,arr1.dtype,type(arr1)

[1 3 5 7]


((4,), 4, 1, dtype('int64'), numpy.ndarray)

In [8]:
# Attributes of 2-dimensional array
print(arr2)
arr2.shape,arr2.size,arr2.ndim,arr2.dtype,type(arr2)

[[ 2  4  6]
 [ 8 10 12]]


((2, 3), 6, 2, dtype('int64'), numpy.ndarray)

In [9]:
# Attributes of 3-dimensional array
print(arr3)
arr3.shape,arr3.ndim,arr3.size,arr3.dtype,type(arr3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


((3, 3, 3), 3, 27, dtype('int64'), numpy.ndarray)

In [10]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df=pd.DataFrame(arr2) # only a two D array can be passed
df

0   1   2
0  2   4   6
1  8  10  12

In [11]:
# Create an array of shape (10, 2) with only ones
ones=np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
# Create an array of shape (7, 2, 3) of only zeros
zeroes=np.zeros((7,2,3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
# Create an array within a range of 0 and 100 with step 3
a=np.arange(0,100,3)
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [14]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rand_arr=np.random.randint(10,size=(7,2))
rand_arr

array([[2, 1],
       [7, 5],
       [6, 0],
       [1, 9],
       [1, 8],
       [3, 9],
       [8, 7]])

In [15]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rand_arr1=np.random.random((3,5))
rand_arr1

array([[0.05402419, 0.81920832, 0.97164267, 0.81707187, 0.42174076],
       [0.83888285, 0.82679588, 0.51751355, 0.93093236, 0.72997236],
       [0.66602979, 0.35908702, 0.17403586, 0.73427274, 0.5543955 ]])

In [16]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
rand_arr2=np.random.randint(10,size=(4,6))
rand_arr2

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

The numbers in the array are the same because random seed is set to 42.

In [17]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
rand_arr3=np.random.randint(10,size=(3,7))
rand_arr3
# Find the unique numbers in the array you just created
np.unique(rand_arr3)

array([0, 1, 2, 3, 4, 6, 8, 9])

In [18]:
# Find the 0'th index of the latest array you created
rand_arr3[0]


array([8, 0, 9, 2, 6, 3, 8])

In [19]:
rand_arr3

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6],
       [1, 3, 8, 1, 9, 8, 9]])

In [20]:
# Get the first 2 rows of latest array you created
rand_arr3[:2]

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]])

In [21]:
# Get the first 2 values of the first 2 rows of the latest array
rand_arr3[:2,:2]

array([[8, 0],
       [2, 4]])

In [22]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
rand_arr4=np.random.randint(10,size=(3,5))
ones1=np.ones((3,5))

In [23]:
# Add the two arrays together
rand_arr4 + ones1

array([[ 5.,  2.,  4.,  7.,  8.],
       [ 3.,  1.,  4.,  2.,  8.],
       [ 4.,  2.,  6.,  6., 10.]])

In [24]:
# Create another array of ones of shape (5, 3)
ones2=np.ones((5,3))

In [29]:
# Try add the array of ones and the other most recent array together
ones2 + ones1

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?
Yes thers an error because shapes aren't same.

How would you fix it? 
reshape the array or transpose it.

In [25]:
# Create another array of ones of shape (3, 5)
ones3=np.ones((3,5))

In [26]:
# Subtract the new array of ones from the other most recent array
ones3 - ones2.T

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
# Multiply the ones array with the latest array
ones3 * ones2.T

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
# Take the latest array to the power of 2 using '**'
ones3 ** 2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
# Do the same thing with np.square()
np.square(ones3)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
# Find the mean of the latest array using np.mean()
np.mean(ones3)

1.0

In [32]:
# Find the maximum of the latest array using np.max()
np.max(ones3)

1.0

In [33]:
# Find the minimum of the latest array using np.min()
np.min(ones3)

1.0

In [34]:
# Find the standard deviation of the latest array
np.std(ones3)

0.0

In [35]:
# Find the variance of the latest array
np.var(ones3)

0.0

In [37]:
# Reshape the latest array to (3, 5, 1)
ones3.reshape(3,5,1)

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [39]:
# Transpose the latest array
ones3.T.shape

(5, 3)

What does the transpose do?
Switches the axes.

In [40]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
rand=np.random.randint(10,size=(3,3))
rand1=np.random.randint(10,size=(3,2))

In [41]:
# Perform a dot product on the two newest arrays you created
np.dot(rand,rand1)

array([[ 48,  33],
       [112, 127],
       [ 76,  70]])

In [43]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
rand2=np.random.randint(10,size=(4,3))
rand3=np.random.randint(10,size=(4,3))

In [44]:
# Perform a dot product on the two newest arrays you created
rand2.dot(rand3)


ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?
by either reshape or transpose one of the array.

In [45]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
rand2.dot(rand3.T)

array([[ 72,  50, 201, 184],
       [ 68,  24, 102,  96],
       [ 49,  16, 114, 106],
       [ 53,  22, 123, 114]])

Notice how performing a transpose allows the dot product to happen.

Why is this?
Because inner shapes of arrays are same.

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [46]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
r=np.random.randint(10,size=(4,5))
r1=np.random.randint(10,size=(4,5))

In [47]:
# Compare the two arrays with '>'
r > r1

array([[False, False, False,  True, False],
       [ True,  True, False,  True, False],
       [False, False, False,  True, False],
       [False, False,  True,  True,  True]])

What happens when you compare the arrays with `>`?
We get a boolean array as result.

In [48]:
# Compare the two arrays with '>='
r >= r1

array([[False, False, False,  True,  True],
       [ True,  True, False,  True, False],
       [False, False, False,  True, False],
       [False, False,  True,  True,  True]])

In [49]:
# Find which elements of the first array are greater than 7
r > 7

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True, False, False]])

In [50]:
# Which parts of each array are equal? (try using '==')
r == 7

array([[ True, False, False, False, False],
       [ True, False, False,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [52]:
# Sort one of the arrays you just created in ascending order
np.sort(r)

array([[0, 1, 6, 6, 7],
       [2, 4, 5, 7, 7],
       [0, 2, 2, 2, 4],
       [0, 4, 6, 6, 9]])

In [ ]:
# Sort the indexes of one of the arrays you just created


In [53]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(r1)

1

In [54]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(r)

2

In [56]:
r

array([[7, 1, 0, 6, 6],
       [7, 4, 2, 7, 5],
       [2, 0, 2, 4, 2],
       [0, 4, 9, 6, 6]])

In [55]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(r,axis=1)

array([0, 0, 3, 2])

In [58]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(r1,axis=0)


array([1, 1, 1, 0, 2])

In [59]:
# Create an array of normally distributed random numbers
rand_n=np.random.randn(100)
rand[:9]

array([[3, 5, 1],
       [9, 1, 9],
       [3, 7, 6]])

In [60]:
# Create an array with 10 evenly spaced numbers between 1 and 100
evenly=np.linspace(1,100,10)
evenly

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.